# Generated by Django 5.2.17 on 2026-09-24 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('staging_object_key', models.CharField(max_length=512, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('declared_size', models.BigIntegerField()),
                ('stored_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING_UPLOAD', 'Pending Upload'), ('UPLOADED', 'Uploaded'), ('DELETED', 'Deleted')], default='PENDING_UPLOAD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_url_expires_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('staging_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['owner', '-created_at'], name='uploads_aud_owner_i_4a71b3_idx'),
                    models.Index(fields=['status', 'created_at'], name='upload_status_created_idx'),
                    models.Index(condition=models.Q(('object_deleted_at__isnull', True), ('status', 'DELETED')), fields=['status'], name='upload_pending_object_cleanup'),
                ],
            },
        ),
    ]
