# Generated by Django 5.2.17 on 2026-09-24 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_profile', models.CharField(choices=[('default', 'Default'), ('standard_only', 'Standard Only')], default='default', max_length=30)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('TRANSCRIBING', 'Transcribing'), ('ANALYSING_STANDARD', 'Analysing Standard'), ('ANALYSING_CUSTOM', 'Analysing Custom'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=30)),
                ('stage_attempts', models.PositiveSmallIntegerField(default=0)),
                ('stage_claim_id', models.CharField(blank=True, max_length=64, null=True)),
                ('stage_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('error_stage', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='uploads.audioupload')),
                ('selected_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='prompts.prompttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STANDARD', 'Standard'), ('TEMPLATE', 'Template')], max_length=20)),
                ('analysis_type', models.CharField(max_length=50)),
                ('prompt_version', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('structured_output', models.JSONField()),
                ('summary', models.TextField()),
                ('usage_metadata', models.JSONField(blank=True, default=dict)),
                ('output_attempts', models.PositiveSmallIntegerField(default=1)),
                ('latency_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analyses.analysisjob')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='prompts.prompttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('detected_language', models.CharField(blank=True, max_length=32)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(max_length=50)),
                ('provider_model', models.CharField(max_length=100)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='analyses.analysisjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'updated_at'], name='analyses_an_status_61e6d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'FAILED'), _negated=True), fields=('audio_upload', 'analysis_profile'), name='analysis_one_live_job_per_upload_profile'),
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.UniqueConstraint(fields=('analysis_job', 'kind'), name='result_one_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'STANDARD'), ('prompt_template__isnull', True)), models.Q(('kind', 'TEMPLATE'), ('prompt_template__isnull', False)), _connector='OR'), name='result_template_matches_kind'),
        ),
    ]
