# Generated by Django 5.2.17 on 2026-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('analysis_type', models.CharField(max_length=50)),
                ('system_instructions', models.TextField(blank=True)),
                ('analysis_instructions', models.TextField()),
                ('filter_config', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'slug', '-version'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='prompt_slug_version_unique'), models.UniqueConstraint(condition=models.Q(('active', True)), fields=('slug',), name='prompt_one_active_version_per_slug')],
            },
        ),
    ]
